config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :samples, only: [:show]
  resources :materials, only: [:show]

  resource :search, only: [] do
    get :material
    get :project
    get :manufacturer
    get :news
  end

  root 'home#index'
end

app/models/sample.rb
# frozen_string_literal: true

class Sample < ApplicationRecord
  self.table_name = 'sample'

  belongs_to :material, foreign_key: :obj_id, class_name: 'Material'
  belongs_to :surface_effect
  belongs_to :manufacturer
  has_many :sample_enclosures

  has_many :sample_color_systems
  has_many :color_systems, through: :sample_color_systems

  has_many :sample_surface_effects
  has_many :surface_effects, through: :sample_surface_effects
  
  belongs_to :sample_position_picture

  default_scope { where(deleted_at: nil).where(display: 1) }

  def name
    if material.present?
      "#{material.name}（样品）"
    end
  end

  def full_no
    if material.present?
      "#{material.no}-#{no}"
    end
  end

  def color_str
    self.color_systems&.collect(&:description)&.join(',')
  end

  # 表面效果描述
  def surface_effect_descriptions
    @_surface_effect_descriptions ||= if self.surface_effects.present?
      self.surface_effects.pluck(:description).join('、')
    else
      self.aq_vein
    end
  end

  def price_range
    price = [low_price, high_price].uniq.join('-')
    price.present? ? "#{price} 元/㎡" : nil
  end
end

app/controllers/api/samples_controller.rb
# frozen_string_literal: true

module Api
  class SamplesController < ApplicationController
    def show
      @sample = Sample.find(params[:id])
    end

    def projects
      case_ids = CasesMaterial.joins(:case_material_samples).where(case_material_samples: { sample_id: params[:id] }).pluck(:case_id)
      @list = Cases.where(id: case_ids)
      @total = @list.count
      page, page_size = pagination_params
      @list = @list.page(page).per(page_size)
    end

    def related_samples
      sample = Sample.find(params[:id])
      material = sample.material
      sample_ids = []
      if material.present? && material.level == 3
        material_id = material.id
        brother_material_ids = Material.where(parent_id: material.parent_id).pluck(:id)
        other_material_ids = Material.where(parent_id: Material.select(:parent_id).where.not(id: material.parent_id).where(grandpa_id: material.grandpa_id)).pluck(:id)
        sample_ids.push(material_id)
        sample_ids.push(*brother_material_ids)
        sample_ids.push(*other_material_ids)
      end
      @list = Sample.where.not(id: sample.id).where(obj_id: sample_ids)
      if material.present? && brother_material_ids.present?
        @list = @list.order(Arel.sql("CASE WHEN obj_id = #{material_id} THEN 2 WHEN obj_id IN (#{brother_material_ids.join(',')}) THEN 1 ELSE 0 END DESC, id ASC")).order(id: :asc)
      end
      @total = @list.count
      page, page_size = pagination_params
      @list = @list.page(page).per(page_size)
    end
  end
end

app/controllers/samples_controller.rb
# frozen_string_literal: true

class SamplesController < ApplicationController
  def show
  end
end

app/views/samples/_other_samples.html.erb
<section class="mr-4" style="width: 400px;">
  <div class="flex flex-row justify-between items-center mt-7 mb-4 border-b-2 border-gray-100 border-solid pb-3">
    <div>
      <span class="text-2xl font-bold ml-px mr-2 under-text-border" style="padding-bottom: 0.9rem">相关样品</span>
      <span class="text-xl font-light">Related Samples</span>
    </div>
    <div class="flex flex-row gap-2">
      <a class="circle-arrow1 w-5 h-5 <%= other_samples.first_page? ? 'cursor-not-allowed disabled' : 'cursor-pointer' %>" href="<%= other_samples_sample_path(id, page_size: other_samples.limit_value, page: other_samples.prev_page) %>">
        <svg class="-ml-0.5" fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="6.2" height="10.5" viewBox="0 0 9.062 16.125">
          <path d="M564.707,561.636L558.343,568l6.364,6.364a1,1,0,0,1-1.414,1.414l-7.071-7.071a1,1,0,0,1,0-1.414l7.071-7.071A1,1,0,0,1,564.707,561.636Z" transform="translate(-555.938 -559.938)"/>
        </svg>
      </a>
      <a class="circle-arrow1 w-5 h-5 <%= other_samples.last_page? || other_samples.next_page.blank? ? 'cursor-not-allowed disabled' : 'cursor-pointer' %>" href="<%= other_samples_sample_path(id, page_size: other_samples.limit_value, page: other_samples.next_page) %>">
        <svg class="-mr-0.5" fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="6.2" height="10.5" viewBox="0 0 9 16">
          <path d="M556.291,561.685l6.32,6.315-6.32,6.315a0.992,0.992,0,0,0,1.4,1.4l7.023-7.016a0.994,0.994,0,0,0,0-1.4l-7.023-7.016A0.992,0.992,0,0,0,556.291,561.685Z" transform="translate(-556 -560)"/>
        </svg>
      </a>
    </div>
  </div>

  <% other_samples.each_with_index do |other_sample, i| %>
    <a class="<%= i == 1 ? 'mt-10' : 'mt-4' -%> mb-4 flex" href="<%= sample_path(other_sample.id) %>" data-turbo="false">
      <div class="flex-none" style="width: 170px; height: 170px;">
        <img class="w-full h-full object-scale-down" src="<%= mat_img_url(other_sample.pic, "") -%>" alt="">
      </div>
      <div class="flex flex-col justify-end mx-4">
        <h2 class="text-base mb-2"><%= other_sample.name %></h2>
        <p class="mt-1 text-xs text-gray-400">样品编号：<%= text_with_default(other_sample.no) -%></p>
        <p class="mt-1 text-xs text-gray-400">表面效果：<%= text_with_default(other_sample.surface_effect_descriptions) -%></p>
        <p class="mt-1 text-xs text-gray-400">色系：<%= text_with_default(other_sample.color_str) -%></p>
        <p class="mt-1 text-xs text-gray-400">供应商：<%= text_with_default(other_sample.manufacturer&.name) -%></p>
      </div>
    </a>
  <% end %>
</section>

app/views/samples/_projects.html.erb
<section class="flex-auto">
  <div class="flex flex-row justify-between items-center mx-4 mt-16 mb-4 border-b-2 border-gray-100 border-solid pb-3">
    <div>
      <span class="text-2xl font-bold ml-px mr-2 under-text-border" style="padding-bottom: 0.9rem">所属案例</span>
      <span class="text-xl font-light">Projects</span>
    </div>
    <div class="flex flex-row gap-2">
      <a class="circle-arrow1 w-5 h-5 <%= cases.first_page? ? 'cursor-not-allowed disabled' : 'cursor-pointer' %>" href="<%= projects_sample_path(id, page_size: cases.limit_value, page: cases.prev_page) %>">
        <svg class="-ml-0.5" fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="6.2" height="10.5" viewBox="0 0 9.062 16.125">
          <path d="M564.707,561.636L558.343,568l6.364,6.364a1,1,0,0,1-1.414,1.414l-7.071-7.071a1,1,0,0,1,0-1.414l7.071-7.071A1,1,0,0,1,564.707,561.636Z" transform="translate(-555.938 -559.938)"/>
        </svg>
      </a>
      <a class="circle-arrow1 w-5 h-5 <%= cases.last_page? || cases.next_page.blank? ? 'cursor-not-allowed disabled' : 'cursor-pointer' %>" href="<%= projects_sample_path(id, page_size: cases.limit_value, page: cases.next_page) %>">
        <svg class="-mr-0.5" fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="6.2" height="10.5" viewBox="0 0 9 16">
          <path d="M556.291,561.685l6.32,6.315-6.32,6.315a0.992,0.992,0,0,0,1.4,1.4l7.023-7.016a0.994,0.994,0,0,0,0-1.4l-7.023-7.016A0.992,0.992,0,0,0,556.291,561.685Z" transform="translate(-556 -560)"/>
        </svg>
      </a>
    </div>
  </div>

  <div class="mx-4 mt-4 grid grid-cols-3 gap-8">
    <% cases.each do |project_case| %>
      <a
        class="block"
        <%= project_case.permissions(current_user)[:info] ? "href=\"#{project_path(project_case)}\"".html_safe : '' %>
      >
        <img class="w-full my-3 h-52 object-cover" src="<%= mat_img_url(project_case.web_cover) -%>" alt="">
        <h3 class="text-lg font-bold"><%= text_with_default(project_case.project_name) -%></h3>
        <p class="text-sm mt-1"><%= text_with_default(project_case.project_location) -%></p>
        <p class="text-sm mt-1"><%= text_with_default(project_case.design_unit) -%></p>
      </a>
    <% end %>
  </div>
</section>

app/views/samples/other_samples.html.erb
<%= turbo_frame_tag "other_samples" do %>
  <%= render partial: 'other_samples', locals: { id: params[:id], other_samples: @other_samples } -%>
<% end %>

app/views/samples/projects.html.erb
<%= turbo_frame_tag "projects" do %>
  <%= render partial: 'projects', locals: { id: params[:id], cases: @cases } -%>
<% end %>

app/views/samples/show.html+phone.erb
<%# 样品名称 %>
<div class="bg-white text-black-6c m-1 px-1.5 py-2.5">
  <div class="my-1 flex">
    <img class="flex-initial" style="max-width: 50%;" src="<%= image_pack_path('static/images/big_sample_picture.jpg') -%>" alt="">
    <dl class="flex-auto ml-2">
      <h3 class="text-base mb-2 font-medium">黄金麻（样品）</h3>
      <p class="text-xs whitespace-nowrap">样品编号：
        <span class="font-medium">A07010</span>
      </p>
      <p class="text-xs whitespace-nowrap">价格区间：
        <span class="font-medium">100-350/㎡</span>
      </p>
      <p class="text-xs whitespace-nowrap">产品/二级分类名称：
        <span class="font-medium">黄金麻</span>
      </p>
      <p class="text-xs whitespace-nowrap">产品/二级分类编号：
        <span class="font-medium">A07013</span>
      </p>
      <p class="text-xs whitespace-nowrap">色系：
        <span class="font-medium">黄色</span>
      </p>
      <p class="text-xs whitespace-nowrap">色号：
        <span class="font-medium">868688</span>
      </p>
      <p class="text-xs whitespace-nowrap">产品规格/型号：
        <span class="font-medium">30*30 cm</span>
      </p>
      <p class="text-xs whitespace-nowrap">表面效果：
        <span class="font-medium">荔枝面</span>
      </p>
      <div class="text-xs whitespace-nowrap" data-controller="modal" data-modal-allow-background-close="true">储存位置：
        <a href="#" data-action="click->modal#open">
          <span class="font-medium underline">A-3-25</span>
        </a>
        <!-- Modal Container -->
        <div data-modal-target="container" data-action="click->modal#closeBackground keyup@window->modal#closeWithKeyboard" class="hidden animated fadeIn fixed inset-0 overflow-y-auto flex items-center justify-center" style="z-index: 9999;">
          <!-- Modal Inner Container -->
          <div class="max-h-screen w-full max-w-7xl relative">
            <!-- Modal Card -->
            <div class="m-1 bg-white rounded shadow">
              <div class="p-8">
                <figure>
                  <img src="<%= image_pack_path('static/images/sample_location.png') -%>" alt="">
                  <figcaption class="text-center mt-2">样板位置: A-3-25</figcaption>
                </figure>
              </div>
            </div>
          </div>
        </div>
      </div>
    </dl>
  </div>
  <h5 class="text-base mt-4">其他样品</h5>
  <div class="pt-2 pb-3 overscroll-x-auto overflow-x-auto shadow-sm">
    <div class="flex flex-nowrap min-w-max">
      <% %w[黄金麻 卡基诺金 世贸金麻 山东黄锈 莆田黄锈 卡拉麦里金 紫点金麻].each_with_index do |name, i| %>
        <% pic_url = "static/new_mat_g#{i+1}.jpg" -%>
        <div class="mx-px first:mx-px w-16">
          <img class="w-full object-contain" src="<%= image_pack_path(pic_url) -%>" alt="">
          <h3 class="text-center text-xs my-2 whitespace-nowrap"><%= name -%></h3>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%# 厂家信息 %>
<div class="bg-white text-black-6c m-1 px-1.5 py-2">
  <h5 class="text-base font-medium my-2">厂家信息</h5>

  <div class="flex bg-gray-200 border border-gray-200 border-solid px-1 my-3">
    <div class="flex justify-center items-center px-2 py-3">
      <img class="w-full border border-gray-300 border-solid" src="<%= image_pack_path('static/images/logo-1-1.jpg') -%>" alt="">
    </div>
    <div class="px-2 py-3">
      <h5 class="text-base font-medium mb-2">东丽石材</h5>
      <p class="text-xs text-gray-700">联系人：13717634543</p>
      <p class="text-xs text-gray-700">邮箱：564738476@qq.com</p>
      <p class="text-xs text-gray-700">厂家地址：山东</p>
      <p class="text-xs text-gray-700">联系电话：65383736</p>
      <p class="text-xs text-gray-700">是否愿意提供材料样品：是</p>
    </div>
  </div>
</div>

<%# 产品案例 %>
<div class="bg-white text-black-6c text-xs px-1.5 pt-2 pb-5 mt-2">
  <h5 class="text-base font-medium m-1">产品案例</h5>
  <div class="grid grid-cols-2 gap-y-2">
    <div class="mx-1">
      <div class="relative">
        <img class="w-full" src="<%= image_pack_path('static/images/project_new_g1.jpg') -%>" alt="">
        <div class="absolute right-1 bottom-1 text-white text-right">
          <p class="text-xs">内部项目</p>
        </div>
        <div class="absolute left-1 bottom-1 text-white text-left">
          <p class="text-white text-right text-xs">荔枝面黄金麻</p>
        </div>
      </div>
      <div class="text-black-6c text-left">
        <p class="text-xs mt-1">融创徐汇滨江壹号 / 上海</p>
        <p class="text-xs">Shanghai West Bund Park</p>
      </div>
    </div>
    <div class="mx-1">
      <div class="relative">
        <img class="w-full" src="<%= image_pack_path('static/images/project_new_g2.jpg') -%>" alt="">
        <div class="absolute right-1 bottom-1 text-white text-right">
          <p class="text-xs">内部项目</p>
        </div>
        <div class="absolute left-1 bottom-1 text-white text-left">
          <p class="text-white text-right text-xs">荔枝面黄金麻</p>
        </div>
      </div>
      <div class="text-black-6c text-left">
        <p class="text-xs mt-1"><%= '合肥北城中央公园中小学'.truncate(10) -%> / 安徽合肥</p>
        <p class="text-xs">Shanghai West Bund Park</p>
      </div>
    </div>
    <div class="mx-1">
      <div class="relative">
        <img class="w-full" src="<%= image_pack_path('static/images/project_new_g3.jpg') -%>" alt="">
        <div class="absolute right-1 bottom-1 text-white text-right">
          <p class="text-xs">内部项目</p>
        </div>
        <div class="absolute left-1 bottom-1 text-white text-left">
          <p class="text-white text-right text-xs">光面黄金麻</p>
        </div>
      </div>
      <div class="text-black-6c text-left">
        <p class="text-xs mt-1"><%= '北京大兴龙湖天街'.truncate(10) -%> / 北京</p>
        <p class="text-xs">Shanghai West Bund Park</p>
      </div>
    </div>
  </div>
</div>

app/views/samples/show.html.erb
<%= render partial: 'shared/header', locals: { } -%>

<p class="mx-4 px-48 pt-8 text-sm text-gray-500">首页 > 石材 > 花岗岩 > 黄金麻 > <span class="text-black">黄金麻样品</span></p>

<div class="flex flex-row px-48">
  <section class="w-full mr-6 max-w-lg lg:max-w-xl xl:max-w-5xl flex flex-col">
    <%# 产品样品 %>
    <div class="mx-4 mt-7 mb-4 border-b-2 border-gray-100 border-solid pb-3">
      <span class="text-2xl font-bold ml-px mr-2 border-b-2 border-gray-900 border-solid" style="padding-bottom: 0.9rem">产品样品</span><span class="text-xl font-light">Samples</span>
    </div>
    <div class="mx-4 mt-4 flex gap-4">
      <img class="w-80 h-80" src="<%= image_pack_path('static/images/big_sample_picture.jpg') -%>" alt="">
      <div class="ml-4 relative">
        <h2 class="text-xl font-medium">黄金麻（样品）：</h2>
        <dl class="absolute bottom-0 w-120 text-sm">
            <dt class="mt-2 inline-block w-1/2">样品编号：</dt>
            <dd class="mt-2 inline">xxxxxxx</dd>

            <dt class="mt-2 inline-block w-1/2">价格：</dt>
            <dd class="mt-2 inline">100-350/㎡</dd>

            <dt class="mt-2 inline-block w-1/2">产品/二级分类名称：</dt>
            <dd class="mt-2 inline">黄金麻</dd>

            <dt class="mt-2 inline-block w-1/2">产品/二级分类编号：</dt>
            <dd class="mt-2 inline">xxxxx</dd>

            <dt class="mt-2 inline-block w-1/2">色系：</dt>
            <dd class="mt-2 inline">黄色</dd>

            <dt class="mt-2 inline-block w-1/2">色号：</dt>
            <dd class="mt-2 inline">xxxx</dd>

            <dt class="mt-2 inline-block w-1/2">产品规格/型号：</dt>
            <dd class="mt-2 inline">30*30CM</dd>

            <dt class="mt-2 inline-block w-1/2">表面效果：</dt>
            <dd class="mt-2 inline">荔枝面</dd>

            <dt class="mt-2 inline-block w-1/2">存储位置：</dt>
            <dd class="mt-2 inline" data-controller="modal" data-modal-allow-background-close="true">
              <a href="#" data-action="click->modal#open">
                <span class="underline">A-3-25</span>
              </a>
              <!-- Modal Container -->
              <div data-modal-target="container" data-action="click->modal#closeBackground keyup@window->modal#closeWithKeyboard" class="hidden animated fadeIn fixed inset-0 overflow-y-auto flex items-center justify-center" style="z-index: 9999;">
                <!-- Modal Inner Container -->
                <div class="max-h-screen w-full max-w-7xl relative">
                  <!-- Modal Card -->
                  <div class="m-1 bg-white rounded shadow">
                    <div class="p-8">
                      <figure>
                        <img src="<%= image_pack_path('static/images/sample_location.png') -%>" alt="">
                        <figcaption class="text-center mt-2">样板位置: A-3-25</figcaption>
                      </figure>
                    </div>
                  </div>
                </div>
              </div>
            </dd>
        </dl>
      </div>
    </div>

    <%# 厂家信息 %>
    <div class="mx-4 mt-16 mb-4 border-b-2 border-gray-100 border-solid pb-3">
      <span class="text-2xl font-bold ml-px mr-2 border-b-2 border-gray-900 border-solid" style="padding-bottom: 0.9rem">厂家信息</span><span class="text-xl font-light">Information</span>
    </div>
    <div class="mx-4 mt-4 grid grid-cols-5 gap-4">
      <div class="row-span-2">
        <div class="border border-gray-300 border-solid mx-auto">
          <img class="w-full" src="<%= image_pack_path('static/images/logo-2-1.jpg') -%>" alt="">
        </div>
      </div>
      <dl class="my-4 border-l border-gray-300 border-solid pl-3 py1">
        <dt class="text-gray-400">厂家名称</dt>
        <dd class="">东利石材</dd>
      </dl>
      <dl class="my-4 border-l border-gray-300 border-solid pl-3 py1">
        <dt class="text-gray-400">联系人</dt>
        <dd class="">XXX</dd>
      </dl>
      <dl class="my-4 border-l border-gray-300 border-solid pl-3 py1">
        <dt class="text-gray-400">邮箱</dt>
        <dd class="">xxx@sample.com</dd>
      </dl>
      <dl></dl>
      <dl class="my-4 border-l border-gray-300 border-solid pl-3 py1">
        <dt class="text-gray-400">厂家地址</dt>
        <dd class="">广东</dd>
      </dl>
      <dl class="my-4 border-l border-gray-300 border-solid pl-3 py1">
        <dt class="text-gray-400">联系电话</dt>
        <dd class="">XXX-12342837</dd>
      </dl>
      <dl class="my-4 border-l border-gray-300 border-solid pl-3 py1">
        <dt class="text-gray-400">是否愿意送样</dt>
        <dd class="">否</dd>
      </dl>
      <dl></dl>
    </div>

    <%# 附件下载 %>
    <div class="mx-4 mt-16 mb-4 border-b-2 border-gray-100 border-solid pb-3">
      <span class="text-2xl font-bold ml-px mr-2 border-b-2 border-gray-900 border-solid" style="padding-bottom: 0.9rem">附件下载</span><span class="text-xl font-light">Download</span>
    </div>
    <div class="mx-4 mt-4 grid grid-cols-5 gap-4">
      <% %w[下载全部 公司介绍 相关证书 产品图册 工艺节点 监测报告 CAD BIM 三视图 其他].each do |word| %>
      <a class="p-4 shadow-tw-dark font-medium bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
        <%= word %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 float-right" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10" />
        </svg>
      </a>
      <% end %>
    </div>

    <%# 所属案例 %>
    <div class="mx-4 mt-16 mb-4 border-b-2 border-gray-100 border-solid pb-3">
      <span class="text-2xl font-bold ml-px mr-2 border-b-2 border-gray-900 border-solid" style="padding-bottom: 0.9rem">所属案例</span><span class="text-xl font-light">Projects</span>
    </div>

    <div class="mx-4 mt-4 mb-16 grid grid-cols-3 gap-8">
      <div>
        <img class="w-full my-3" src="<%= image_pack_path('static/images/project_new_g3.jpg') -%>" alt="">
        <h3 class="text-base font-medium">沈阳国际软件园</h3>
        <p class="text-sm mt-1">辽宁省沈阳市</p>
        <p class="text-sm mt-1">上海天华/建筑十所</p>
      </div>
      <div>
        <img class="w-full my-3" src="<%= image_pack_path('static/images/project_new_g4.jpg') -%>" alt="">
        <h3 class="text-xl font-medium">华润宁波万象汇</h3>
        <p class="text-sm mt-1">浙江省宁波市</p>
        <p class="text-sm mt-1">上海天华/公建一所（总）</p>
      </div>
      <div>
        <img class="w-full my-3" src="<%= image_pack_path('static/images/project_new_g5.jpg') -%>" alt="">
        <h3 class="text-base font-medium">龙湖·中铁建·云璟</h3>
        <p class="text-sm mt-1">辽宁省沈阳市</p>
        <p class="text-sm mt-1">上海天华/建筑四所</p>
      </div>
    </div>
  </section>

  <%# 其他样品 %>
  <section class="flex-auto">
    <div class="mr-4 mt-7 mb-4 border-b-2 border-gray-100 border-solid pb-3">
      <span class="text-2xl font-bold ml-px mr-2 border-b-2 border-gray-900 border-solid" style="padding-bottom: 0.9rem">其他样品</span><span class="text-xl font-light">Other Samples</span>
<svg class="h-6 w-6 float-right mt-1" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <path d="M511.936 61.568a448 448 0 0 0-447.552 447.552 448 448 0 0 0 447.552 447.552 448 448 0 0 0 447.552-447.552A448 448 0 0 0 511.936 61.568z m0 831.104a384 384 0 0 1-383.552-383.552 384 384 0 0 1 383.552-383.552 384 384 0 0 1 383.552 383.552 383.936 383.936 0 0 1-383.552 383.552z" p-id="2135"></path>
  <path d="M386.112 278.784a31.872 31.872 0 0 1 44.992-0.32l207.104 207.168c6.464 6.4 9.28 14.912 8.96 23.424a30.912 30.912 0 0 1-8.96 23.616L431.04 739.84c-12.224 12.352-32.384 12.224-44.864-0.256s-12.608-32.64-0.384-44.992l185.408-185.408-185.344-185.472a31.744 31.744 0 0 1 0.256-44.928z" p-id="2136"></path>
</svg>
<svg class="h-6 w-6 float-right mt-1 mr-1 lg:mr-2 xl:mr-3" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <path d="M511.936 61.568a448 448 0 0 0-447.552 447.552 448 448 0 0 0 447.552 447.552 448 448 0 0 0 447.552-447.552A448 448 0 0 0 511.936 61.568z m0 831.104a384 384 0 0 1-383.552-383.552 384 384 0 0 1 383.552-383.552 384 384 0 0 1 383.552 383.552 383.936 383.936 0 0 1-383.552 383.552z" p-id="2277"></path>
  <path d="M637.76 278.784a31.872 31.872 0 0 0-44.992-0.32L385.6 485.632a30.912 30.912 0 0 0-8.96 23.424 31.36 31.36 0 0 0 8.96 23.616l207.168 207.168c12.224 12.352 32.384 12.224 44.864-0.256s12.608-32.64 0.384-44.992L452.608 509.184l185.344-185.408a31.744 31.744 0 0 0-0.192-44.992z" p-id="2278"></path>
</svg>
    </div>

    <% (1..4).each do |i| %>
      <div class="mr-4 <%= i == 1 ? 'mt-10' : 'mt-4' -%> mb-4 flex">
        <img class="w-1/2" src="<%= image_pack_path("static/images/sample_side_p#{i}.jpg") -%>" alt="">
        <div class="flex flex-col justify-end mx-4">
          <h2 class="text-base mb-2">黄金麻（样品）</h2>
          <p class="mt-1 text-xs text-gray-400">样品编号：xxxx</p>
          <p class="mt-1 text-xs text-gray-400">表面工艺：xxxxxxx</p>
          <p class="mt-1 text-xs text-gray-400">色系：黄色</p>
          <p class="mt-1 text-xs text-gray-400">厂家：xxxxxx</p>
        </div>
      </div>
    <% end %>
  </section>
</div>